version: '2.0'
services:
    php_fpm:
        build:
            context: .
            dockerfile: Dockerfile
        # image: php:7.0.9-fpm
        volumes:
         - $PWD/php:/usr/share/nginx/php
    web_nginx:
        image: nginx
        volumes:
        #  Volumen para sitio estatico
         - $PWD/html:/usr/share/nginx/html
        #  Volumen de sitio de tipo php
         - $PWD/php:/usr/share/nginx/php
        #  Volumen para configuracion Default nginx
         - $PWD/nginx:/etc/nginx/conf.d
        ports:
         - "8080:80" # Puerto para sitio estatico
         - "8181:8181" # Puerto para sitio php
        # environment:
        #  - NGINX_PORT=80
        # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        depends_on:
         - php_fpm