version: '2.0'
services:
    php_fpm:
        image: php:7.0.9-fpm
        volumes:
         - $PWD/php:/usr/share/nginx/php
    web_nginx:
        image: nginx
        volumes:
        #  Volumen para sitio
         - $PWD/html:/usr/share/nginx/html
         - $PWD/php:/usr/share/nginx/php
        #  Volumen para configuracion Default nginx
         - $PWD/nginx:/etc/nginx/conf.d
        ports:
         - "8080:80"
         - "8181:8181"
        environment:
         - NGINX_PORT=80
        # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        depends_on:
         - php_fpm